blank_issues_enabled: false
contact_links:
  - name: Keil MDK Support
    url: https://www.keil.arm.com/support/#:~:text=Keil%20Studio%20for%20VS%20Code
    about: Please raise questions and issues here.
